In [1]:
import numpy as np
import pandas as pd
import data_clean_utils
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer, KNNImputer, MissingIndicator
from sklearn.preprocessing import OneHotEncoder, StandardScaler, LabelEncoder, MinMaxScaler, PowerTransformer, OrdinalEncoder
from sklearn.model_selection import train_test_split

In [2]:
import dagshub
dagshub.init(repo_owner='rahulpatel16092005', repo_name='swiggy-delivery-time-prediction-system', mlflow=True)

Accessing as rahulpatel16092005

Repository swiggy-delivery-time-prediction-system doesn't exist, creating it under current user.

Initialized MLflow to track repo "rahulpatel16092005/swiggy-delivery-time-prediction-system"

Repository rahulpatel16092005/swiggy-delivery-time-prediction-system initialized!

In [3]:
import mlflow
mlflow.set_tracking_uri("https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow")
mlflow.set_experiment("Exp 2 - Model Selection")

c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2026/03/31 09:21:00 INFO mlflow.tracking.fluent: Experiment with name 'Exp 2 - Model Selection' does not exist. Creating a new experiment.

<Experiment: artifact_location='mlflow-artifacts:/3d5edc471f454a79b0e83ec92dfeddce', creation_time=1774929062243, experiment_id='2', last_update_time=1774929062243, lifecycle_stage='active', name='Exp 2 - Model Selection', tags={}, workspace='default'>

In [4]:
from sklearn import set_config

set_config(transform_output="pandas")

In [13]:
df=pd.read_csv("swiggy_cleaned.csv")

In [14]:
df.head()

,rider_id,age,ratings,restaurant_latitude,restaurant_longitude,delivery_latitude,delivery_longitude,order_date,weather,traffic,...,city_name,order_day,order_month,order_day_of_week,is_weekend,pickup_time_minutes,order_time_hour,order_time_of_day,distance,distance_type
0,INDORES13DEL02,37.0,4.9,22.745049,75.892471,22.765049,75.912471,2022-03-19,sunny,high,...,INDO,19,3,saturday,1,15.0,11.0,morning,3.025149,short
1,BANGRES18DEL02,34.0,4.5,12.913041,77.683237,13.043041,77.813237,2022-03-25,stormy,jam,...,BANG,25,3,friday,0,5.0,19.0,evening,20.183530,very_long
2,BANGRES19DEL01,23.0,4.4,12.914264,77.678400,12.924264,77.688400,2022-03-19,sandstorms,low,...,BANG,19,3,saturday,1,15.0,8.0,morning,1.552758,short
3,COIMBRES13DEL02,38.0,4.7,11.003669,76.976494,11.053669,77.026494,2022-04-05,sunny,medium,...,COIMB,5,4,tuesday,0,10.0,18.0,evening,7.790401,medium
4,CHENRES12DEL01,32.0,4.6,12.972793,80.249982,13.012793,80.289982,2022-03-26,cloudy,high,...,CHEN,26,3,saturday,1,15.0,13.0,afternoon,6.210138,medium

In [15]:
# drop columns not required for model input

columns_to_drop =  ['rider_id',
                    'restaurant_latitude',
                    'restaurant_longitude',
                    'delivery_latitude',
                    'delivery_longitude',
                    'order_date',
                    "order_time_hour",
                    "order_day",
                    "city_name",
                    "order_day_of_week",
                    "order_month"]

df.drop(columns=columns_to_drop, inplace=True)

df

,age,ratings,weather,traffic,vehicle_condition,type_of_order,type_of_vehicle,multiple_deliveries,festival,city_type,time_taken,is_weekend,pickup_time_minutes,order_time_of_day,distance,distance_type
0,37.0,4.9,sunny,high,2,snack,motorcycle,0.0,no,urban,24,1,15.0,morning,3.025149,short
1,34.0,4.5,stormy,jam,2,snack,scooter,1.0,no,metropolitian,33,0,5.0,evening,20.183530,very_long
2,23.0,4.4,sandstorms,low,0,drinks,motorcycle,1.0,no,urban,26,1,15.0,morning,1.552758,short
3,38.0,4.7,sunny,medium,0,buffet,motorcycle,1.0,no,metropolitian,21,0,10.0,evening,7.790401,medium
4,32.0,4.6,cloudy,high,1,snack,scooter,1.0,no,metropolitian,30,1,15.0,afternoon,6.210138,medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45497,30.0,4.8,windy,high,1,meal,motorcycle,0.0,no,metropolitian,32,0,10.0,morning,1.489846,short
45498,21.0,4.6,windy,jam,0,buffet,motorcycle,1.0,no,metropolitian,36,0,15.0,evening,NaN,NaN
45499,30.0,4.9,cloudy,low,1,drinks,scooter,0.0,no,metropolitian,16,0,15.0,night,4.657195,short
45500,20.0,4.7,cloudy,high,0,snack,motorcycle,1.0,no,metropolitian,26,0,5.0,afternoon,6.232393,medium
45501,23.0,4.9,fog,medium,2,snack,scooter,1.0,no,metropolitian,36,0,5.0,afternoon,12.074396,long

In [16]:
temp_df=df.copy().dropna()

In [17]:
# split into X and y

X = temp_df.drop(columns='time_taken')
y = temp_df['time_taken']

In [18]:
# train test split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [19]:
print("The size of train data is",X_train.shape)
print("The shape of test data is",X_test.shape)

The size of train data is (30156, 15)
The shape of test data is (7539, 15)

In [20]:
# missing values in train data

X_train.isna().sum()

age                    0
ratings                0
weather                0
traffic                0
vehicle_condition      0
type_of_order          0
type_of_vehicle        0
multiple_deliveries    0
festival               0
city_type              0
is_weekend             0
pickup_time_minutes    0
order_time_of_day      0
distance               0
distance_type          0
dtype: int64

In [21]:
# transform target column

pt = PowerTransformer()

y_train_pt = pt.fit_transform(y_train.values.reshape(-1,1))
y_test_pt = pt.transform(y_test.values.reshape(-1,1))

In [22]:
X.head()

,age,ratings,weather,traffic,vehicle_condition,type_of_order,type_of_vehicle,multiple_deliveries,festival,city_type,is_weekend,pickup_time_minutes,order_time_of_day,distance,distance_type
0,37.0,4.9,sunny,high,2,snack,motorcycle,0.0,no,urban,1,15.0,morning,3.025149,short
1,34.0,4.5,stormy,jam,2,snack,scooter,1.0,no,metropolitian,0,5.0,evening,20.183530,very_long
2,23.0,4.4,sandstorms,low,0,drinks,motorcycle,1.0,no,urban,1,15.0,morning,1.552758,short
3,38.0,4.7,sunny,medium,0,buffet,motorcycle,1.0,no,metropolitian,0,10.0,evening,7.790401,medium
4,32.0,4.6,cloudy,high,1,snack,scooter,1.0,no,metropolitian,1,15.0,afternoon,6.210138,medium

In [23]:
num_cols = ["age","ratings","pickup_time_minutes","distance"]

nominal_cat_cols = ['weather',
                    'type_of_order',
                    'type_of_vehicle',
                    "festival",
                    "city_type",
                    "is_weekend",
                    "order_time_of_day"]

ordinal_cat_cols = ["traffic","distance_type"]

In [24]:
# generate order for ordinal encoding

traffic_order = ["low","medium","high","jam"]

distance_type_order = ["short","medium","long","very_long"]

In [25]:
# build a preprocessor

preprocessor = ColumnTransformer(transformers=[
    ("scale", MinMaxScaler(), num_cols),
    ("nominal_encode", OneHotEncoder(drop="first",handle_unknown="ignore",
                                     sparse_output=False), nominal_cat_cols),
    ("ordinal_encode", OrdinalEncoder(categories=[traffic_order,distance_type_order],
                                      encoded_missing_value=-999,
                                      handle_unknown="use_encoded_value",
                                      unknown_value=-1), ordinal_cat_cols)
],remainder="passthrough",n_jobs=-1,force_int_remainder_cols=False,verbose_feature_names_out=False)


preprocessor

ColumnTransformer(force_int_remainder_cols=False, n_jobs=-1,
                  remainder='passthrough',
                  transformers=[('scale', MinMaxScaler(),
                                 ['age', 'ratings', 'pickup_time_minutes',
                                  'distance']),
                                ('nominal_encode',
                                 OneHotEncoder(drop='first',
                                               handle_unknown='ignore',
                                               sparse_output=False),
                                 ['weather', 'type_of_order', 'type_of_vehicle',
                                  'festival', 'city_type', 'is_weekend',
                                  'order_time_of_day']),
                                ('ordinal_encode',
                                 OrdinalEncoder(categories=[['low', 'medium',
                                                             'high', 'jam'],
                                                            ['short', 'medium',
                                                             'long',
                                                             'very_long']],
                                                encoded_missing_value=-999,
                                                handle_unknown='use_encoded_value',
                                                unknown_value=-1),
                                 ['traffic', 'distance_type'])],
                  verbose_feature_names_out=False)

In [26]:
# build the pipeline

processing_pipeline = Pipeline(steps=[
                               
                                ("preprocess",preprocessor)
                                
                            ])

processing_pipeline

Pipeline(steps=[('preprocess',
                 ColumnTransformer(force_int_remainder_cols=False, n_jobs=-1,
                                   remainder='passthrough',
                                   transformers=[('scale', MinMaxScaler(),
                                                  ['age', 'ratings',
                                                   'pickup_time_minutes',
                                                   'distance']),
                                                 ('nominal_encode',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['weather', 'type_of_order',
                                                   'type_of_vehicle',
                                                   'festival', 'city_type',
                                                   'is_weekend',
                                                   'order_time_of_day']),
                                                 ('ordinal_encode',
                                                  OrdinalEncoder(categories=[['low',
                                                                              'medium',
                                                                              'high',
                                                                              'jam'],
                                                                             ['short',
                                                                              'medium',
                                                                              'long',
                                                                              'very_long']],
                                                                 encoded_missing_value=-999,
                                                                 handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['traffic',
                                                   'distance_type'])],
                                   verbose_feature_names_out=False))])

In [27]:
# do data preprocessing

X_train_trans = processing_pipeline.fit_transform(X_train)

X_test_trans = processing_pipeline.transform(X_test)

c:\Users\hp\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\compose\_column_transformer.py:978: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(

In [30]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
import optuna

In [34]:
def objective(trial):
    with mlflow.start_run(nested=True):
        model_name = trial.suggest_categorical("model",["SVM","RF","KNN","GB","XGB","LGBM"])

        if model_name == "SVM":
            kernel_svm = trial.suggest_categorical("kernel_svm",["linear","poly","rbf"])
            if kernel_svm == "linear":
                c_linear = trial.suggest_float("c_linear",0,10)
                model = SVR(C=c_linear,kernel="linear")

            elif kernel_svm == "poly":
                c_poly = trial.suggest_float("c_poly",0,10)
                degree_poly = trial.suggest_int("degree_poly",1,5)
                model = SVR(C=c_poly,degree=degree_poly,
                            kernel="poly")

            else:
                c_rbf = trial.suggest_float("c_rbf",0,100)
                gamma_rbf = trial.suggest_float("gamma_rbf",0,10)
                model = SVR(C=c_rbf,gamma=gamma_rbf,
                            kernel="rbf")

        elif model_name == "RF":
            n_estimators_rf = trial.suggest_int("n_estimators_rf",10,200)
            max_depth_rf = trial.suggest_int("max_depth_rf",2,20)
            model = RandomForestRegressor(n_estimators=n_estimators_rf,
                                        max_depth=max_depth_rf,
                                        random_state=42,
                                        n_jobs=-1)

        elif model_name == "GB":
            n_estimators_gb = trial.suggest_int("n_estimators_gb",10,200)
            learning_rate_gb = trial.suggest_float("learning_rate_gb",0,1)
            max_depth_gb = trial.suggest_int("max_depth_gb",2,20)
            model = GradientBoostingRegressor(n_estimators=n_estimators_gb,
                                                learning_rate=learning_rate_gb,
                                                max_depth=max_depth_gb,
                                                random_state=42)

        elif model_name == "KNN":
            n_neighbors_knn = trial.suggest_int("n_neighbors_knn",1,25)
            weights_knn = trial.suggest_categorical("weights_knn",["uniform","distance"])
            model = KNeighborsRegressor(n_neighbors=n_neighbors_knn,
                                        weights=weights_knn,n_jobs=-1)

        elif model_name == "XGB":
            n_estimators_xgb = trial.suggest_int("n_estimators_xgb",10,200)
            learning_rate_xgb = trial.suggest_float("learning_rate_xgb",0.1,0.5)
            max_depth_xgb = trial.suggest_int("max_depth_xgb",2,20)
            model = XGBRegressor(n_estimators=n_estimators_xgb,
                                    learning_rate=learning_rate_xgb,
                                    max_depth=max_depth_xgb,
                                    random_state=42,
                                    n_jobs=-1)

        elif model_name == "LGBM":
            n_estimators_lgbm = trial.suggest_int("n_estimators_lgbm",10,200)
            learning_rate_lgbm = trial.suggest_float("learning_rate_lgbm",0.1,0.5)
            max_depth_lgbm = trial.suggest_int("max_depth_lgbm",2,20)
            model = LGBMRegressor(n_estimators=n_estimators_lgbm,
                                    learning_rate=learning_rate_lgbm,
                                    max_depth=max_depth_lgbm,
                                    random_state=42)


        # train the model
        model.fit(X_train_trans,y_train_pt.values.ravel())

        # log model params
        mlflow.log_params(model.get_params())

        # get the predictions
        y_pred_train = model.predict(X_train_trans)
        y_pred_test = model.predict(X_test_trans)

        # get the actual predictions values
        y_pred_train_org = pt.inverse_transform(y_pred_train.reshape(-1,1))
        y_pred_test_org = pt.inverse_transform(y_pred_test.reshape(-1,1))

        # calculate the error
        error = mean_absolute_error(y_test,y_pred_test_org)

        # log model_name
        mlflow.log_param("model",model_name)

        # log error
        mlflow.log_metric("MAE",error)

        return error

In [35]:
# create optuna study
study = optuna.create_study(direction="minimize",study_name="model_selection")

with mlflow.start_run(run_name="Best Model") as parent:
    # optimize the objective function
    study.optimize(objective,n_trials=30,n_jobs=-1)

    # log the best parameters
    mlflow.log_params(study.best_params)

    # log the best score
    mlflow.log_metric("best_score",study.best_value)

[I 2026-03-31 09:34:17,076] A new study created in memory with name: model_selection

🏃 View run whimsical-shad-498 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2/runs/a387c042e7f441ac9635de8f5ffbef82
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2

[I 2026-03-31 09:34:40,273] Trial 4 finished with value: 3.7719229428015764 and parameters: {'model': 'GB', 'n_estimators_gb': 91, 'learning_rate_gb': 0.142934180774131, 'max_depth_gb': 2}. Best is trial 4 with value: 3.7719229428015764.

🏃 View run resilient-bass-848 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2/runs/4cdd58365a1047a6b7cc4c38ddeae11d
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2

[I 2026-03-31 09:34:41,010] Trial 6 finished with value: 4.191284032553859 and parameters: {'model': 'KNN', 'n_neighbors_knn': 15, 'weights_knn': 'distance'}. Best is trial 4 with value: 3.7719229428015764.

🏃 View run languid-crane-227 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2/runs/e2300fed9d69496cae97b13d08a21535
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2

[I 2026-03-31 09:34:45,974] Trial 1 finished with value: 3.0642407405988528 and parameters: {'model': 'LGBM', 'n_estimators_lgbm': 46, 'learning_rate_lgbm': 0.2986309352436609, 'max_depth_lgbm': 10}. Best is trial 1 with value: 3.0642407405988528.

🏃 View run exultant-sow-318 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2/runs/337b1671426548808e7ad3295968b2bf
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2

[I 2026-03-31 09:34:55,097] Trial 7 finished with value: 3.1839635372161865 and parameters: {'model': 'XGB', 'n_estimators_xgb': 163, 'learning_rate_xgb': 0.24304909287275744, 'max_depth_xgb': 9}. Best is trial 1 with value: 3.0642407405988528.

🏃 View run puzzled-hare-973 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2/runs/61bc204945d0499ebe6c6680b9c0c850
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2
🏃 View run delightful-ray-713 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2/runs/4893f6247faa439ab922d81540d099e3
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2

[I 2026-03-31 09:35:00,083] Trial 9 finished with value: 3.0520215821455525 and parameters: {'model': 'LGBM', 'n_estimators_lgbm': 49, 'learning_rate_lgbm': 0.17121960159141753, 'max_depth_lgbm': 15}. Best is trial 9 with value: 3.0520215821455525.
[I 2026-03-31 09:35:01,394] Trial 8 finished with value: 3.176592927529825 and parameters: {'model': 'LGBM', 'n_estimators_lgbm': 88, 'learning_rate_lgbm': 0.3791626936219499, 'max_depth_lgbm': 4}. Best is trial 9 with value: 3.0520215821455525.

🏃 View run bright-gnat-92 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2/runs/0b90bb58715a4d04b37521e5f4f99ff3
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2

[I 2026-03-31 09:35:09,934] Trial 10 finished with value: 3.4805277048312147 and parameters: {'model': 'GB', 'n_estimators_gb': 11, 'learning_rate_gb': 0.651390655095466, 'max_depth_gb': 13}. Best is trial 9 with value: 3.0520215821455525.

🏃 View run polite-worm-132 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2/runs/73680a22fbba433e9cd696620b83789f
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2

[I 2026-03-31 09:35:15,088] Trial 12 finished with value: 3.123927354812622 and parameters: {'model': 'XGB', 'n_estimators_xgb': 166, 'learning_rate_xgb': 0.408394069769236, 'max_depth_xgb': 5}. Best is trial 9 with value: 3.0520215821455525.

🏃 View run tasteful-whale-945 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2/runs/a4cf1e1dbc7b4d0a9e82ba989803eb36
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2

[I 2026-03-31 09:35:21,044] Trial 13 finished with value: 4.26854561069738 and parameters: {'model': 'KNN', 'n_neighbors_knn': 16, 'weights_knn': 'uniform'}. Best is trial 9 with value: 3.0520215821455525.

🏃 View run classy-rat-800 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2/runs/b001686f2f9f4aab92bdf820095df477
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2

[I 2026-03-31 09:35:26,342] Trial 14 finished with value: 4.305362533150618 and parameters: {'model': 'KNN', 'n_neighbors_knn': 5, 'weights_knn': 'distance'}. Best is trial 9 with value: 3.0520215821455525.

🏃 View run skillful-doe-73 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2/runs/1758f791436d42d5b80be18d6da06e9d
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2

[I 2026-03-31 09:36:11,979] Trial 15 finished with value: 4.265031238675697 and parameters: {'model': 'KNN', 'n_neighbors_knn': 15, 'weights_knn': 'uniform'}. Best is trial 9 with value: 3.0520215821455525.

🏃 View run overjoyed-cub-886 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2/runs/dd88ab1a3fd74bb2b546b807a4daa13f
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2

[I 2026-03-31 09:36:55,550] Trial 18 finished with value: 3.3080080308124487 and parameters: {'model': 'LGBM', 'n_estimators_lgbm': 20, 'learning_rate_lgbm': 0.12451992918659241, 'max_depth_lgbm': 16}. Best is trial 9 with value: 3.0520215821455525.

🏃 View run likeable-cow-444 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2/runs/74ca2bcdee704e50b87c98d43ba30994
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2

[I 2026-03-31 09:37:54,882] Trial 19 finished with value: 3.0536326776797638 and parameters: {'model': 'LGBM', 'n_estimators_lgbm': 47, 'learning_rate_lgbm': 0.1981337651945397, 'max_depth_lgbm': 12}. Best is trial 9 with value: 3.0520215821455525.

🏃 View run exultant-carp-117 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2/runs/72b817efb0094f808cb3bd604d51e216
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2

[I 2026-03-31 09:38:00,052] Trial 20 finished with value: 4.296810833229073 and parameters: {'model': 'RF', 'n_estimators_rf': 43, 'max_depth_rf': 5}. Best is trial 9 with value: 3.0520215821455525.

🏃 View run rumbling-owl-239 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2/runs/508e231b4a284f93b10bcfb8f8c204b7
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2

[I 2026-03-31 09:40:32,849] Trial 5 finished with value: 3.7971062840887235 and parameters: {'model': 'SVM', 'kernel_svm': 'poly', 'c_poly': 1.1559829777247999, 'degree_poly': 3}. Best is trial 9 with value: 3.0520215821455525.

🏃 View run spiffy-grub-504 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2/runs/35495c2d3c4f42e8aa4f41a2a5096e3b
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2

[I 2026-03-31 09:41:40,875] Trial 22 finished with value: 3.053234338153407 and parameters: {'model': 'LGBM', 'n_estimators_lgbm': 185, 'learning_rate_lgbm': 0.16773770276737585, 'max_depth_lgbm': 15}. Best is trial 9 with value: 3.0520215821455525.

🏃 View run respected-stork-301 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2/runs/eaaaa03695694e5fa8eae5c5f585f553
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2

[I 2026-03-31 09:42:29,666] Trial 23 finished with value: 3.0579660521581866 and parameters: {'model': 'LGBM', 'n_estimators_lgbm': 189, 'learning_rate_lgbm': 0.21126609137435193, 'max_depth_lgbm': 19}. Best is trial 9 with value: 3.0520215821455525.

🏃 View run nimble-worm-769 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2/runs/f21ed35f69a449fd92b14fe48eb1e3f8
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2

[I 2026-03-31 09:42:50,895] Trial 24 finished with value: 3.077219614312489 and parameters: {'model': 'RF', 'n_estimators_rf': 196, 'max_depth_rf': 20}. Best is trial 9 with value: 3.0520215821455525.

🏃 View run fortunate-rook-656 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2/runs/45681bd0aa7246f583b95f297f0b63c9
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2

[I 2026-03-31 09:47:09,684] Trial 16 finished with value: 4.675447207207843 and parameters: {'model': 'SVM', 'kernel_svm': 'linear', 'c_linear': 3.3075042622355655}. Best is trial 9 with value: 3.0520215821455525.

🏃 View run big-elk-20 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2/runs/c2369e5a0afb4230958d33479052f3a7
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2

[I 2026-03-31 09:48:16,091] Trial 26 finished with value: 3.023696042295672 and parameters: {'model': 'LGBM', 'n_estimators_lgbm': 181, 'learning_rate_lgbm': 0.1131787683298488, 'max_depth_lgbm': 14}. Best is trial 26 with value: 3.023696042295672.

🏃 View run zealous-pug-25 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2/runs/9170125ecb5340d48fb162d745d09ebd
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2

[I 2026-03-31 09:49:00,540] Trial 27 finished with value: 3.0286972614696945 and parameters: {'model': 'LGBM', 'n_estimators_lgbm': 129, 'learning_rate_lgbm': 0.11322445797343814, 'max_depth_lgbm': 11}. Best is trial 26 with value: 3.023696042295672.

🏃 View run glamorous-squid-945 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2/runs/659acc6aea7841a294d5c6cf5add7f12
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2

[I 2026-03-31 09:51:43,756] Trial 17 finished with value: 4.675509672190076 and parameters: {'model': 'SVM', 'kernel_svm': 'linear', 'c_linear': 7.5780458235727854}. Best is trial 26 with value: 3.023696042295672.

🏃 View run placid-cat-808 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2/runs/336614a64d94490ba94b460965f5a924
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2

[I 2026-03-31 09:51:49,289] Trial 28 finished with value: 3.041292996814953 and parameters: {'model': 'LGBM', 'n_estimators_lgbm': 135, 'learning_rate_lgbm': 0.10187717173031796, 'max_depth_lgbm': 11}. Best is trial 26 with value: 3.023696042295672.

🏃 View run capable-newt-708 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2/runs/2065498c2c694410b2ee7832235e7c23
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2

[I 2026-03-31 09:51:52,706] Trial 29 finished with value: 3.029801402887916 and parameters: {'model': 'LGBM', 'n_estimators_lgbm': 131, 'learning_rate_lgbm': 0.10697292797306593, 'max_depth_lgbm': 11}. Best is trial 26 with value: 3.023696042295672.

🏃 View run victorious-hound-6 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2/runs/1e996e49ab244344828a43cb5f07e73c
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2

[I 2026-03-31 09:52:58,955] Trial 2 finished with value: 5.799398172125174 and parameters: {'model': 'SVM', 'kernel_svm': 'rbf', 'c_rbf': 96.12372483721511, 'gamma_rbf': 2.7927175513315983}. Best is trial 26 with value: 3.023696042295672.

🏃 View run amusing-flea-222 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2/runs/a29d5680c1b1451c8ba63af023710345
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2

[I 2026-03-31 09:54:28,527] Trial 0 finished with value: 4.675497239000412 and parameters: {'model': 'SVM', 'kernel_svm': 'linear', 'c_linear': 9.04341683340706}. Best is trial 26 with value: 3.023696042295672.

🏃 View run kindly-skunk-706 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2/runs/8d0ed72c514a4d768de0fed2b7c4b7d2
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2

[I 2026-03-31 09:54:57,170] Trial 21 finished with value: 3.7598953524577645 and parameters: {'model': 'SVM', 'kernel_svm': 'poly', 'c_poly': 0.6213875218537419, 'degree_poly': 5}. Best is trial 26 with value: 3.023696042295672.

🏃 View run unruly-stag-162 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2/runs/a9f09197b6514150b0a7cfec3f35f9b6
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2

[I 2026-03-31 09:55:04,280] Trial 11 finished with value: 6.63929216596057 and parameters: {'model': 'SVM', 'kernel_svm': 'rbf', 'c_rbf': 39.76475883797767, 'gamma_rbf': 9.858005122266313}. Best is trial 26 with value: 3.023696042295672.

🏃 View run redolent-smelt-689 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2/runs/3bcd469dd88a48aeb0730504689b9c66
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2

[I 2026-03-31 09:56:06,921] Trial 3 finished with value: 4.815428224650307 and parameters: {'model': 'SVM', 'kernel_svm': 'rbf', 'c_rbf': 51.72864322175836, 'gamma_rbf': 1.5043437481066446}. Best is trial 26 with value: 3.023696042295672.

🏃 View run sassy-hare-248 at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2/runs/42c78cf0ab6247788a8508d9760d7a9e
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2

[I 2026-03-31 09:56:38,258] Trial 25 finished with value: 6.190269233732252 and parameters: {'model': 'SVM', 'kernel_svm': 'rbf', 'c_rbf': 28.87374668754389, 'gamma_rbf': 4.19010898053956}. Best is trial 26 with value: 3.023696042295672.

🏃 View run Best Model at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2/runs/c106ff71e6e044f19cfe3d22d8a0ae16
🧪 View experiment at: https://dagshub.com/rahulpatel16092005/swiggy-delivery-time-prediction.mlflow/#/experiments/2

In [31]:
from sklearn.metrics import mean_absolute_error

In [36]:
study.best_params

{'model': 'LGBM',
 'n_estimators_lgbm': 181,
 'learning_rate_lgbm': 0.1131787683298488,
 'max_depth_lgbm': 14}

In [39]:

study.best_value

3.023696042295672

In [37]:
params={
    'n_estimators_lgbm': 181,
 'learning_rate_lgbm': 0.1131787683298488,
 'max_depth_lgbm': 14

}

In [40]:
lgbm=LGBMRegressor(**params)
lgbm.fit(X_train_trans,y_train_pt.values.ravel())

[LightGBM] [Warning] Unknown parameter: learning_rate_lgbm
[LightGBM] [Warning] Unknown parameter: n_estimators_lgbm
[LightGBM] [Warning] Unknown parameter: max_depth_lgbm
[LightGBM] [Warning] Unknown parameter: learning_rate_lgbm
[LightGBM] [Warning] Unknown parameter: n_estimators_lgbm
[LightGBM] [Warning] Unknown parameter: max_depth_lgbm
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001061 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 352
[LightGBM] [Info] Number of data points in the train set: 30156, number of used features: 25
[LightGBM] [Info] Start training from score -0.000000

LGBMRegressor(learning_rate_lgbm=0.1131787683298488, max_depth_lgbm=14,
              n_estimators_lgbm=181)

In [41]:
# get the predictions
y_pred_train = lgbm.predict(X_train_trans)
y_pred_test = lgbm.predict(X_test_trans)

[LightGBM] [Warning] Unknown parameter: learning_rate_lgbm
[LightGBM] [Warning] Unknown parameter: n_estimators_lgbm
[LightGBM] [Warning] Unknown parameter: max_depth_lgbm
[LightGBM] [Warning] Unknown parameter: learning_rate_lgbm
[LightGBM] [Warning] Unknown parameter: n_estimators_lgbm
[LightGBM] [Warning] Unknown parameter: max_depth_lgbm

In [42]:
# get the actual predictions values

y_pred_train_org = pt.inverse_transform(y_pred_train.reshape(-1,1))
y_pred_test_org = pt.inverse_transform(y_pred_test.reshape(-1,1))

In [43]:
from sklearn.metrics import mean_absolute_error, r2_score

print(f"The train error is {mean_absolute_error(y_train,y_pred_train_org):.2f} minutes")
print(f"The test error is {mean_absolute_error(y_test,y_pred_test_org):.2f} minutes")

The train error is 2.97 minutes
The test error is 3.05 minutes

In [44]:
print(f"The train r2 score is {r2_score(y_train,y_pred_train_org):.2f}")
print(f"The test r2 score is {r2_score(y_test,y_pred_test_org):.2f}")

The train r2 score is 0.85
The test r2 score is 0.83

In [45]:
# dataframe of results

study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_c_linear,params_c_poly,params_c_rbf,params_degree_poly,params_gamma_rbf,...,params_max_depth_rf,params_max_depth_xgb,params_model,params_n_estimators_gb,params_n_estimators_lgbm,params_n_estimators_rf,params_n_estimators_xgb,params_n_neighbors_knn,params_weights_knn,state
0,0,4.675497,2026-03-31 09:34:18.399073,2026-03-31 09:54:28.527746,0 days 00:20:10.128673,9.043417,NaN,NaN,NaN,NaN,...,NaN,NaN,SVM,NaN,NaN,NaN,NaN,NaN,NaN,COMPLETE
1,1,3.064241,2026-03-31 09:34:18.401339,2026-03-31 09:34:45.974546,0 days 00:00:27.573207,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,LGBM,NaN,46.0,NaN,NaN,NaN,NaN,COMPLETE
2,2,5.799398,2026-03-31 09:34:18.403349,2026-03-31 09:52:58.955123,0 days 00:18:40.551774,NaN,NaN,96.123725,NaN,2.792718,...,NaN,NaN,SVM,NaN,NaN,NaN,NaN,NaN,NaN,COMPLETE
3,3,4.815428,2026-03-31 09:34:18.406899,2026-03-31 09:56:06.921047,0 days 00:21:48.514148,NaN,NaN,51.728643,NaN,1.504344,...,NaN,NaN,SVM,NaN,NaN,NaN,NaN,NaN,NaN,COMPLETE
4,4,3.771923,2026-03-31 09:34:18.408675,2026-03-31 09:34:40.271287,0 days 00:00:21.862612,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,GB,91.0,NaN,NaN,NaN,NaN,NaN,COMPLETE
5,5,3.797106,2026-03-31 09:34:18.409956,2026-03-31 09:40:32.848020,0 days 00:06:14.438064,NaN,1.155983,NaN,3.0,NaN,...,NaN,NaN,SVM,NaN,NaN,NaN,NaN,NaN,NaN,COMPLETE
6,6,4.191284,2026-03-31 09:34:18.411129,2026-03-31 09:34:41.009645,0 days 00:00:22.598516,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,KNN,NaN,NaN,NaN,NaN,15.0,distance,COMPLETE
7,7,3.183964,2026-03-31 09:34:18.412767,2026-03-31 09:34:55.097746,0 days 00:00:36.684979,NaN,NaN,NaN,NaN,NaN,...,NaN,9.0,XGB,NaN,NaN,NaN,163.0,NaN,NaN,COMPLETE
8,8,3.176593,2026-03-31 09:34:40.307253,2026-03-31 09:35:01.392747,0 days 00:00:21.085494,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,LGBM,NaN,88.0,NaN,NaN,NaN,NaN,COMPLETE
9,9,3.052022,2026-03-31 09:34:41.045411,2026-03-31 09:35:00.082898,0 days 00:00:19.037487,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,LGBM,NaN,49.0,NaN,NaN,NaN,NaN,COMPLETE
10,10,3.480528,2026-03-31 09:34:46.105580,2026-03-31 09:35:09.933845,0 days 00:00:23.828265,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,GB,11.0,NaN,NaN,NaN,NaN,NaN,COMPLETE
11,11,6.639292,2026-03-31 09:34:55.112940,2026-03-31 09:55:04.279909,0 days 00:20:09.166969,NaN,NaN,39.764759,NaN,9.858005,...,NaN,NaN,SVM,NaN,NaN,NaN,NaN,NaN,NaN,COMPLETE
12,12,3.123927,2026-03-31 09:35:00.089365,2026-03-31 09:35:15.087817,0 days 00:00:14.998452,NaN,NaN,NaN,NaN,NaN,...,NaN,5.0,XGB,NaN,NaN,NaN,166.0,NaN,NaN,COMPLETE
13,13,4.268546,2026-03-31 09:35:01.408168,2026-03-31 09:35:21.044157,0 days 00:00:19.635989,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,KNN,NaN,NaN,NaN,NaN,16.0,uniform,COMPLETE
14,14,4.305363,2026-03-31 09:35:09.942026,2026-03-31 09:35:26.341880,0 days 00:00:16.399854,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,KNN,NaN,NaN,NaN,NaN,5.0,distance,COMPLETE
15,15,4.265031,2026-03-31 09:35:15.097714,2026-03-31 09:36:11.977253,0 days 00:00:56.879539,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,KNN,NaN,NaN,NaN,NaN,15.0,uniform,COMPLETE
16,16,4.675447,2026-03-31 09:35:21.062066,2026-03-31 09:47:09.684756,0 days 00:11:48.622690,3.307504,NaN,NaN,NaN,NaN,...,NaN,NaN,SVM,NaN,NaN,NaN,NaN,NaN,NaN,COMPLETE
17,17,4.675510,2026-03-31 09:35:26.352240,2026-03-31 09:51:43.755923,0 days 00:16:17.403683,7.578046,NaN,NaN,NaN,NaN,...,NaN,NaN,SVM,NaN,NaN,NaN,NaN,NaN,NaN,COMPLETE
18,18,3.308008,2026-03-31 09:36:12.004503,2026-03-31 09:36:55.549782,0 days 00:00:43.545279,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,LGBM,NaN,20.0,NaN,NaN,NaN,NaN,COMPLETE
19,19,3.053633,2026-03-31 09:36:55.556141,2026-03-31 09:37:54.882242,0 days 00:00:59.326101,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,LGBM,NaN,47.0,NaN,NaN,NaN,NaN,COMPLETE
20,20,4.296811,2026-03-31 09:37:54.891912,2026-03-31 09:38:00.051936,0 days 00:00:05.160024,NaN,NaN,NaN,NaN,NaN,...,5.0,NaN,RF,NaN,NaN,43.0,NaN,NaN,NaN,COMPLETE
21,21,3.759895,2026-03-31 09:38:00.061540,2026-03-31 09:54:57.170268,0 days 00:16:57.108728,NaN,0.621388,NaN,5.0,NaN,...,NaN,NaN,SVM,NaN,NaN,NaN,NaN,NaN,NaN,COMPLETE
22,22,3.053234,2026-03-31 09:40:32.864907,2026-03-31 09:41:40.875781,0 days 00:01:08.010874,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,LGBM,NaN,185.0,NaN,NaN,NaN,NaN,COMPLETE
23,23,3.057966,2026-03-31 09:41:40.880252,2026-03-31 09:42:29.666487,0 days 00:00:48.786235,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,LGBM,NaN,189.0,NaN,NaN,NaN,NaN,COMPLETE
24,24,3.077220,2026-03-31 09:42:29.673545,2026-03-31 09:42:50.894732,0 days 00:00:21.221187,NaN,NaN,NaN,NaN,NaN,...,20.0,NaN,RF,NaN,NaN,196.0,NaN,NaN,NaN,COMPLETE
25,25,6.190269,2026-03-31 09:42:50.902341,2026-03-31 09:56:38.258014,0 days 00:13:47.355673,NaN,NaN,28.873747,NaN,4.190109,...,NaN,NaN,SVM,NaN,NaN,NaN,NaN,NaN,NaN,COMPLETE
26,26,3.023696,2026-03-31 09:47:09.690834,2026-03-31 09:48:16.091238,0 days 00:01:06.400404,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,LGBM,NaN,181.0,NaN,NaN,NaN,NaN,COMPLETE
27,27,3.028697,2026-03-31 09:48:16.102153,2026-03-31 09:49:00.540518,0 days 00:00:44.438365,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,LGBM,NaN,129.0,NaN,NaN,NaN,NaN,COMPLETE
28,28,3.041293,2026-03-31 09:49:00.545552,2026-03-31 09:51:49.289537,0 days 00:02:48.743985,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,LGBM,NaN,135.0,NaN,NaN,NaN,NaN,COMPLETE
29,29,3.029801,2026-03-31 09:51:43.763107,2026-03-31 09:51:52.706475,0 days 00:00:08.943368,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,LGBM,NaN,131.0,NaN,NaN,NaN,NaN,COMPLETE

In [46]:
# model frequency

study.trials_dataframe()['params_model'].value_counts()

params_model
LGBM    11
SVM      9
KNN      4
GB       2
XGB      2
RF       2
Name: count, dtype: int64

In [47]:
# avg scores for all tested models

study.trials_dataframe().groupby("params_model")['value'].mean().sort_values()

params_model
LGBM    3.080835
XGB     3.153945
GB      3.626225
RF      3.687015
KNN     4.257556
SVM     5.003094
Name: value, dtype: float64

In [48]:
from sklearn.compose import TransformedTargetRegressor

model = TransformedTargetRegressor(regressor=lgbm,
                                    transformer=pt)

In [49]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(model,
                         X_train_trans,
                         y_train,
                         scoring="neg_mean_absolute_error",
                         cv=5,n_jobs=-1)

scores

array([-3.08875699, -3.07222064, -3.07556268, -3.09114835, -3.04729934])

In [50]:
# mean score

- scores.mean()

np.float64(3.0749975999523964)